let stockProductos = [
   {id: 1, nombre: "Buzo blanco Dolce&Gabana", cantidad: 1, precio: 5400, img: './multimedia/imagenes/buzos/buzoblanco.jpeg'},
   {id: 2, nombre: "Buzo gris Abercrombie", cantidad: 1, precio: 5600, img: './multimedia/imagenes/buzos/buzonegro.jpeg'},
   {id: 3, nombre: "Buzo Negro Tommy Hilfiger", cantidad: 1, precio: 4700, img: './multimedia/imagenes/buzos/buzonegro1.jpeg'},
   {id: 4, nombre: "Buzo Rojo Hollister", cantidad: 1, precio: 5000, img: './multimedia/imagenes/buzos/buzorojo.jpeg'},
   {id: 5, nombre: "Nike Negras Air 70", cantidad: 1, precio: 6000, img: './multimedia/imagenes/nike/nikenegra.jpg'},
   {id: 6, nombre: "Nike Airmax Colors", cantidad: 1, precio: 6700, img: './multimedia/imagenes/nike/nikecolores.jpg'},
   {id: 7, nombre: "Nike Zoom Azul y Rosa", cantidad: 1, precio: 6400, img: './multimedia/imagenes/nike/nikoazulrosa.jpg'},
   {id: 8, nombre: "Rave Gris Unisex", cantidad: 1, precio: 5500, img: './multimedia/imagenes/rave/ravegris.jpg'},
   {id: 9, nombre: "RaveLona Unisex Clasicas Beige", cantidad: 1, precio: 5200, img: './multimedia/imagenes/rave/ravemarron.jpg'},
   {id: 10, nombre: "Rave Negra de lona Unisex", cantidad: 1, precio: 5500, img: './multimedia/imagenes/rave/ravenegra.jpg'},
   {id: 11, nombre: "floops",cantidad: 1, precio: 2000, img: './multimedia/imagenes/verano/flops.jpeg'},
   {id: 12, nombre: "ojotas", cantidad: 1, precio: 2500, img: './multimedia/imagenes/verano/ojotas.jpeg'},
   {id: 13, nombre: "sandalias", cantidad: 1, precio: 2300, img: './multimedia/imagenes/verano/sandalias.jpeg'}, 
]  
